local cfg = {}

cfg.showgarage = {
  vehicles = {
                --Tilbud biler
				{name = "Baller LE LWB", costs = 1850000, description = {}, model = "baller4"},
				{name = "Dominator GTX", costs = 2500000, description = {}, model = "dominator3"},
				{name = "Maserati Ghibli S", costs = 7500000, description = {}, model = "ghibli"},
				--Tilbuds motorcykler
				{name = "Randers knallert", costs = 100000, description = {}, model = "faggio"},
				--Compacts
				{name = "Blista", costs = 97500, description = {}, model = "blista"},
				{name = "Brioso R/A", costs = 120000, description = {}, model = "brioso"},
				{name = "Dilettante", costs = 52500, description = {}, model = "dilettante"},
				{name = "Futo", costs = 112500, description = {}, model = "futo"},
				{name = "Issi", costs = 412500, description = {}, model = "issi2"},
				{name = "Panto", costs = 24000, description = {}, model = "panto"},
				{name = "Peugeot 308", costs = 385000, description = {}, model = "peug308"},
				{name = "Prairie", costs = 56000, description = {}, model = "prairie"},
				{name = "Rhapsody", costs = 25000, description = {}, model = "rhapsody"},
				{name = "VW Golf 6", costs = 685000, description = {}, model = "vwmk6"},
				--Coupes
  				{name = "Cognoscenti Cabrio", costs = 300000, description = {}, model = "cogcabrio"},
				{name = "Exemplar", costs = 615000, description = {}, model = "exemplar"},
				{name = "F620", costs = 375000, description = {}, model = "f620"},
				{name = "Felon", costs = 675000, description = {}, model = "felon"},
				{name = "Felon GT", costs = 480000, description = {}, model = "felon2"},
				{name = "Jackal", costs = 630000, description = {}, model = "jackal"},
				{name = "Oracle", costs = 210000, description = {}, model = "oracle"},
				{name = "Oracle XS", costs = 180000, description = {}, model = "oracle2"},
				{name = "Sentinel", costs = 360000, description = {}, model = "sentinel"},
				{name = "Sentinel XS", costs = 330000, description = {}, model = "sentinel2"},
				{name = "Windsor", costs = 1275000, description = {}, model = "windsor"},
				{name = "Windsor Drop", costs = 1750000, description = {}, model = "windsor2"},
				{name = "Zion", costs = 187500, description = {}, model = "zion"},
				{name = "Zion Cabrio", costs = 225000, description = {}, model = "zion2"},
				--Sportsbiler
				{name = "Chevrolet Corvette C1", costs = 2900000, description = {}, model = "cc1"},
				{name = "Ferrari 308 Quattrovalvole", costs = 2500000, description = {}, model = "308"},
				{name = "Fiat 124 Spider", costs = 680000, description = {}, model = "124spider"},
				{name = "Nissan GT-R35", costs = 4800000, description = {}, model = "r35"},
				{name = "Ford Focus RS", costs = 1275000, description = {}, model = "focusrs"},
				{name = "Audi TTS", costs = 2250000, description = {}, model = "tts"},
				{name = "BMW M3 F80", costs = 2775000, description = {}, model = "m3f80"},
				{name = "BMW M4 F82", costs = 3000000, description = {}, model = "f82"},
				{name = "BMW M2", costs = 1875000, description = {}, model = "m2"},
				{name = "BMW M3 E92", costs = 2625000, description = {}, model = "bmwm3"},
				{name = "9F", costs = 2700000, description = {}, model = "ninef"},
				{name = "9F Cabrio", costs = 3600000, description = {}, model = "ninef2"},
				{name = "Specter Custom", costs = 1110000, description = {}, model = "specter2"},
				{name = "Elegy RH8", costs = 270000, description = {}, model = "elegy"},
				{name = "Alpha", costs = 1200000, description = {}, model = "alpha"},
				{name = "Banshee", costs = 570000, description = {}, model = "banshee"},
				{name = "Bestia GTS", costs = 1065000, description = {}, model = "bestiagts"},
				{name = "Blista Compact", costs = 180000, description = {}, model = "blista"},
				{name = "Buffalo", costs = 420000, description = {}, model = "buffalo"},
				{name = "Itali GTB", costs = 945000, description = {}, model = "italigtb"},
				{name = "Buffalo S", costs = 480000, description = {}, model = "buffalo2"},
				{name = "Carbonizzare", costs = 506250, description = {}, model = "carbonizzare"},
				{name = "Comet", costs = 270000, description = {}, model = "comet2"},
				{name = "Coquette", costs = 420000, description = {}, model = "coquette"},
				{name = "Drift Tampa", costs = 1875000, description = {}, model = "tampa2"},
				{name = "Furore GT", costs = 420000, description = {}, model = "furoregt"},
				{name = "Fusilade", costs = 112500, description = {}, model = "fusilade"},
				{name = "Jester", costs = 570000, description = {}, model = "jester"},
				{name = "Kuruma", costs = 375000, description = {}, model = "kuruma"},
				{name = "Lynx", costs = 250500, description = {}, model = "lynx"},
				{name = "Massacro", costs = 1950000, description = {}, model = "massacro"},
				{name = "Omnis", costs = 390000, description = {}, model = "omnis"},
				{name = "Penumbra", costs = 54000, description = {}, model = "penumbra"},
				{name = "Rapid GT", costs = 180000, description = {}, model = "rapidgt"},
				{name = "Rapid GT Convertible", costs = 192000, description = {}, model = "rapidgt2"},
				{name = "Schafter V12", costs = 750000, description = {}, model = "schafter3"},
				{name = "Sultan", costs = 42000, description = {}, model = "sultan"},
				{name = "Surano", costs = 6525000, description = {}, model = "surano"},
				{name = "Tropos", costs = 337000, description = {}, model = "tropos"},
				{name = "Verkierer", costs = 270000, description = {}, model = "verlierer2"},
				{name = "Sultan RS", costs = 660000, description = {}, model = "sultanrs"},
				{name = "Hijak Ruston", costs = 1355000, description = {}, model = "ruston"},
				--Classics
				{name = "Casco", costs = 660000, description = {}, model = "casco"},
				{name = "Coquette Classic", costs = 1775000, description = {}, model = "coquette2"},
				{name = "JB 700", costs = 960000, description = {}, model = "jb700"},
				{name = "Pigalle", costs = 375000, description = {}, model = "pigalle"},
				{name = "Stinger", costs = 885000, description = {}, model = "stinger"},
				{name = "Stinger GT", costs = 1155000, description = {}, model = "stingergt"},
				{name = "Stirling GT", costs = 1650000, description = {}, model = "feltzer3"},
				{name = "Z-Type", costs = 2250000, description = {}, model = "ztype"},
				--Superbiler
				{name = "Porsche Panamera", costs = 15750000, description = {}, model = "panamera17turbo"},
				{name = "Aston Martin Vanquish", costs = 13875000, description = {}, model = "ast"},
				{name = "Ford GT", costs = 13350000, description = {}, model = "gt17"},
				--Muskelbiler
				{name = "Tornado Convertible", costs = 630000, description = {}, model = "tornado2"},
				{name = "Blade", costs = 495000, description = {}, model = "blade"},
				{name = "Mustang GT", costs = 1605000, description = {}, model = "mgt"},
				{name = "Buccaneer", costs =123000, description = {}, model = "buccaneer"},
				{name = "Chino", costs = 93750, description = {}, model = "chino"},
				{name = "Coquette BlackFin", costs = 186000, description = {}, model = "coquette3"},
				{name = "Dominator", costs = 465000, description = {}, model = "dominator"},
				{name = "Dukes", costs = 172000, description = {}, model = "dukes"},
				{name = "Gauntlet", costs = 363000, description = {}, model = "gauntlet"},
				{name = "Hotknife", costs = 365000, description = {}, model = "hotknife"},
				{name = "Faction", costs = 168000, description = {}, model = "faction"},
				{name = "Nightshade", costs = 487500, description = {}, model = "nightshade"},
				{name = "Picador", costs = 44900, description = {}, model = "picador"},
				{name = "Sabre Turbo", costs = 187500, description = {}, model = "sabregt"},
				{name = "Tampa", costs = 356000, description = {}, model = "tampa"},
				{name = "Virgo", costs = 375000, description = {}, model = "virgo"},
				{name = "Vigero", costs = 91500, description = {}, model = "vigero"},
				{name = "Albany Hermes", costs = 1525000, description = {}, model = "hermes"},
				{name = "Declasse Voodoo Custom", costs = 715000, description = {}, model = "voodoo"},
				--Offroad
				{name = "Nissan Titan", costs = 2900000, description = {}, model = "nissantitan17"},
				{name = "Ford Raptor", costs = 3200000, description = {}, model = "f150"},
                {name = "Jeep Wrangler", costs = 735000, description = {}, model = "wrangler86"},
				{name = "Bifta", costs =96000, description = {}, model = "bifta"},
				{name = "Blazer", costs = 22000, description = {}, model = "blazer"},
				{name = "Brawler", costs = 525000, description = {}, model = "brawler"},
				{name = "Dubsta 6x6", costs = 935000, description = {}, model = "dubsta3"},
				{name = "Dune Buggy", costs = 40000, description = {}, model = "dune"},
				{name = "Rebel", costs = 50000, description = {}, model = "rebel2"},
				{name = "Sandking", costs = 36000, description = {}, model = "sandking"},
				{name = "Trophy Truck", costs = 1225000, description = {}, model = "trophytruck"},
				--SUVs
				{name = "BMW X5 E53", costs = 1275000, description = {}, model = "x5e53"},
				{name = "Baller", costs = 735000, description = {}, model = "baller"},
				{name = "Cavalcade", costs = 330000, description = {}, model = "cavalcade"},
				{name = "Granger", costs = 665000, description = {}, model = "granger"},
				{name = "Huntley S", costs = 465000, description = {}, model = "huntley"},
				{name = "Landstalker", costs = 83000, description = {}, model = "landstalker"},
				{name = "Radius", costs = 62000, description = {}, model = "radi"},
				{name = "Rocoto", costs = 780000, description = {}, model = "rocoto"},
				{name = "Seminole", costs = 165000, description = {}, model = "seminole"},
				{name = "XLS", costs = 465000, description = {}, model = "xls"},
				--Varevogne
				{name = "Mercedes V250", costs = 1850000, description = {}, model = "v250"},
				{name = "Bison", costs = 90000, description = {}, model = "bison"},
				{name = "Bobcat XL", costs = 67000, description = {}, model = "bobcatxl"},
				{name = "Gang Burrito", costs = 88500, description = {}, model = "gburrito"},
				{name = "Journey", costs = 65000, description = {}, model = "journey"},
				{name = "Minivan", costs = 65000, description = {}, model = "minivan"},
				{name = "Paradise", costs = 55000, description = {}, model = "paradise"},
				{name = "Rumpo", costs = 230000, description = {}, model = "rumpo"},
				{name = "Surfer", costs = 29000, description = {}, model = "surfer"},
				{name = "Youga", costs = 104000, description = {}, model = "youga"},
				--Sedans
				{name = "Ford Mondeo", costs = 580000, description = {}, model = "mondeo"},
				{name = "Mercedes CLA45", costs = 1920000, description = {}, model = "cla45sb"},
				{name = "Audi A3", costs = 1200000, description = {}, model = "2015a3"},
				{name = "Volkswagen Passat B8", costs = 955000, description = {}, model = "vwstance"},
				{name = "Audi S4 Avant", costs = 2100000, description = {}, model = "s4avant"},
				{name = "Tesla Model S", costs = 2175000, description = {}, model = "models"},
				{name = "Audi RS7", costs = 3750000, description = {}, model = "rs7"},
				{name = "Audi A8", costs = 3375000, description = {}, model = "a8fsi"},
				{name = "Audi S4 B5", costs = 1000000, description = {}, model = "b5s4"},
				{name = "Volvo 850R", costs = 600000, description = {}, model = "v850r"},
				{name = "BMW M3 E30", costs = 675000, description = {}, model = "m3e30"},
				{name = "Asea", costs = 450000, description = {}, model = "asea"},
				{name = "Asterope", costs = 195000, description = {}, model = "asterope"},
				{name = "Fugitive", costs = 385000, description = {}, model = "fugitive"},
				{name = "Glendale", costs = 65000, description = {}, model = "glendale"},
				{name = "Ingot", costs = 22000, description = {}, model = "ingot"},
				{name = "Intruder", costs = 65000, description = {}, model = "intruder"},
				{name = "Premier", costs = 20000, description = {}, model = "premier"},
				{name = "Primo", costs = 80000, description = {}, model = "primo"},
				{name = "Primo Custom", costs = 195000, description = {}, model = "primo2"},
				{name = "Regina", costs = 22000, description = {}, model = "regina"},
				{name = "Schafter", costs = 645000, description = {}, model = "schafter2"},
				{name = "Stanier", costs = 38000, description = {}, model = "stanier"},
				{name = "Stratum", costs = 39000, description = {}, model = "stratum"},
				{name = "Stretch", costs = 475000, description = {}, model = "stretch"},
				{name = "Super Diamond", costs = 685000, description = {}, model = "superd"},
				{name = "Surge", costs = 228000, description = {}, model = "surge"},
				{name = "Tailgater", costs = 165000, description = {}, model = "tailgater"},
				{name = "Warrener", costs = 88000, description = {}, model = "warrener"},
				{name = "Washington", costs = 85000, description = {}, model = "washington"},
				--Motorcykler
				{name = "Akuma", costs = 88000, description = {}, model = "akuma"},
				{name = "Bagger", costs = 100000, description = {}, model = "bagger"},
				{name = "Bati 801", costs = 35000, description = {}, model = "bati"},
				{name = "Bati 801RR", costs = 35000, description = {}, model = "bati2"},
				{name = "BF400", costs = 385000, description = {}, model = "bf400"},
				{name = "Carbon RS", costs = 80000, description = {}, model = "carbonrs"},
				{name = "Cliffhanger", costs = 325000, description = {}, model = "cliffhanger"},
				{name = "Daemon", costs = 88000, description = {}, model = "daemon"},
				{name = "Double T", costs = 22000, description = {}, model = "double"},
				{name = "Enduro", costs = 88000, description = {}, model = "enduro"},
				{name = "Faggio", costs = 36000, description = {}, model = "faggio2"},
				{name = "Faggio", costs = 34000, description = {}, model = "faggio3"},
				{name = "Gargoyle", costs = 240000, description = {}, model = "gargoyle"},
				{name = "Hakuchou", costs = 160000, description = {}, model = "hakuchou"},
				{name = "Hexer", costs = 35000, description = {}, model = "hexer"},
				{name = "Innovation", costs = 160000, description = {}, model = "innovation"},
				{name = "Lectro", costs = 120000, description = {}, model = "lectro"},
				{name = "Nemesis", costs = 22000, description = {}, model = "nemesis"},
				{name = "PCJ-600", costs = 19000, description = {}, model = "pcj"},
				{name = "Ruffian", costs = 19000, description = {}, model = "ruffian"},
				{name = "Sanchez", costs = 17000, description = {}, model = "sanchez"},
				{name = "Sovereign", costs = 140000, description = {}, model = "sovereign"},
				{name = "Thrust", costs = 135000, description = {}, model = "thrust"},
				{name = "Vader", costs = 64000, description = {}, model = "vader"},
				{name = "Vindicator", costs = 340000, description = {}, model = "vindicator"},
				--Cykler
				{name = "BMX", costs = 6000, description = {}, model = "bmx"},
				{name = "Fixter", costs = 6000, description = {}, model = "fixter"},
				{name = "Scorcher", costs = 9000, description = {}, model = "scorcher"},
				{name = "Cruiser", costs = 9500, description = {}, model = "cruiser"},
				{name = "Tribike 1", costs = 14500, description = {}, model = "tribike"},
				{name = "Tribike 2", costs = 14500, description = {}, model = "tribike2"},
				{name = "Tribike 3", costs = 14500, description = {}, model = "tribike3"}
  }
}

return cfg