cfg = {}

cfg.chance = 5.998 -- chance of being unlocked in percentage

cfg.blacklist = { -- vehicles that will always be locked when spawned naturally
  "9F",
  "9F Cabrio",
  "Adder",
  "Asea",
  "Asterope",
  "Baller",
  "Banshee",
  "BeeJay XL",
  "Bison",
  "Blista",
  "Bobcat XL",
  "Bodhi",
  "Buccaneer",
  "Buffalo",
  "Buffalo S",
  "Bullet",
  "Carbonizzare",
  "Cavalcade",
  "Cavalcade",
  "Cheetah",
  "Cognoscenti Cabrio",
  "Comet",
  "Coquette",
  "Diletantte",
  "Dominator",
  "Dubsta",
  "Dune Buggy",
  "Duneloader",
  "Emperor",
  "Entity XF",
  "Exemplar",
  "F620",
  "Felon",
  "Felon GT",
  "Feltzer",
  "FQ 2",
  "Fugitive",
  "Fusilade",
  "Futo",
  "Gauntlet",
  "Granger",
  "Gresley",
  "Habanero",
  "Infernus",
  "Ingot",
  "Injection",
  "Intruder",
  "Issi",
  "Jackal",
  "JB 700",
  "Landstalker",
  "Manana",
  "Mesa",
  "Mesa (Merryweather)",
  "Monroe",
  "Oracle",
  "Oracle",
  "Patriot",
  "Penumbra",
  "Peyote",
  "Phoenix",
  "Picador",
  "Prairie",
  "Premier",
  "Primo",
  "Radius",
  "Rancher XL",
  "Rapit GT",
  "Rapit GT (Cabrio)",
  "Rat-Loader",
  "Rebel",
  "Regina",
  "Rocoto",
  "Romero Hearse",
  "Ruiner",
  "Sabre Turbo",
  "Sadler",
  "Sandking SWB",
  "Sandking XL",
  "Schafter",
  "Schwartzer",
  "Seminole",
  "Sentinel",
  "Sentinel XS",
  "Serrano",
  "Space Docker",
  "Stanier",
  "Stinger",
  "Stinger GT",
  "Stratum",
  "Stretch",
  "Sultan",
  "Super Diamond",
  "Surano",
  "Surge",
  "Tailgater",
  "Taxi",
  "Tornado",
  "Tornado (Cabrio)",
  "Vacca",
  "Vigero",
  "Voltic",
  "Voodoo",
  "Washington",
  "Z-Type",
  "Zion",
  "Zion Cabrio",
  "Akuma",
  "Bagger",
  "Bati 801",
  "Bati 801RR",
  "Blazer",
  "Carbon RS",
  "Daemon",
  "Double-T",
  "Faggio",
  "Hakuchou",
  "Hexer",
  "Innovation",
  "Nemesis",
  "PCJ 600",
  "Ruffian",
  "Sanchez",
  "Sanchez 2",
  "Sovereign",
  "Thrust",
  "Vader",
  "Vindicator"
}